
package registros.Presentation;

import java.util.Date;
import javax.swing.JOptionPane;
import registros.Infraestructura.Models.ClienteModelo;
import registros.Services.ServicioClientes;


public class Cliente extends javax.swing.JFrame {

    private ServicioClientes serviciocliente;
   
    public Cliente() {
        initComponents();
        setLocationRelativeTo(null);

        serviciocliente =new ServicioClientes("postgres", "091100", "localhost", "5432", "Registros");  
    }
    
    public void cargardatos(ClienteModelo modelo){
        etiqidcliente.setText(String.valueOf(modelo.getIdcliente()));
        etiqidpersona.setText(String.valueOf(modelo.getIdPersona()));
        cbestado.setSelectedItem(modelo.getEstado());
        DateIngreso.setDate(modelo.getFecha_ingreso());   
    }
        
    private void consultarClientePorId(String id) {
        cargardatos(serviciocliente.consultarClientePorId(Integer.parseInt(id)));
       
    }
    
    private void guardarCliente() {
        Date fechaSeleccionada = DateIngreso.getDate();
        ClienteModelo cliente = new ClienteModelo();
        cliente.setIdcliente(Integer.parseInt(etiqidcliente.getText()));
        cliente.setIdPersona(Integer.parseInt(etiqidpersona.getText()));  
        cliente.setEstado(cbestado.getSelectedItem().toString());  
        cliente.setFecha_ingreso(fechaSeleccionada);

        String resultado = serviciocliente.registrarCliente(cliente);
        JOptionPane.showMessageDialog(this, resultado);

    LimpiarCampos();
}
    
    private void actualizarCliente(){
        Date fechaSeleccionada = DateIngreso.getDate();
        ClienteModelo cliente = new ClienteModelo();
        cliente.setIdcliente(Integer.parseInt(etiqidcliente.getText()));
        cliente.setIdPersona(Integer.parseInt(etiqidpersona.getText()));  
        cliente.setEstado(cbestado.getSelectedItem().toString()); 
        cliente.setFecha_ingreso(fechaSeleccionada);
  
        String resultado = serviciocliente.modificarCliente(cliente);
        JOptionPane.showMessageDialog(this, resultado);

    LimpiarCampos();
    }
    
    private void LimpiarCampos() {
        etiqidcliente.setText("");
        etiqidpersona.setText("");
        DateIngreso.setDate(null);
        cbestado.setSelectedIndex(0);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidcliente = new javax.swing.JLabel();
        txtidpersona = new javax.swing.JLabel();
        txtingreso = new javax.swing.JLabel();
        txtestado = new javax.swing.JLabel();
        etiqidcliente = new javax.swing.JTextField();
        etiqidpersona = new javax.swing.JTextField();
        DateIngreso = new com.toedter.calendar.JDateChooser();
        btnguadar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnaactualizar = new javax.swing.JButton();
        cbestado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");

        txtidcliente.setText("ID Cliente");

        txtidpersona.setText("ID Persona");

        txtingreso.setText("Fecha Ingreso");

        txtestado.setText("Estado");

        etiqidcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                etiqidclienteKeyPressed(evt);
            }
        });

        btnguadar.setText("Guardar");
        btnguadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguadarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnaactualizar.setText("Actualizar");
        btnaactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaactualizarActionPerformed(evt);
            }
        });

        cbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Activo", "Inactivo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(btnguadar)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnaactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnsalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtidcliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtidpersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtestado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateIngreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiqidpersona)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etiqidcliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnconsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbestado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidcliente)
                    .addComponent(btnconsultar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqidpersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidpersona))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtingreso)
                    .addComponent(DateIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtestado)
                    .addComponent(cbestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalir)
                    .addComponent(btnaactualizar)
                    .addComponent(btneliminar)
                    .addComponent(btnguadar))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        if(JOptionPane.showConfirmDialog(null,"Deseas salir del formulario?")== JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
       String idEliminar = etiqidcliente.getText().trim();

    if (!idEliminar.isEmpty()) {
        try {
            int id = Integer.parseInt(idEliminar);
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este cliente?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
            if (confirmacion == JOptionPane.YES_OPTION) {
                String mensajeEliminar = serviciocliente.eliminarCliente(id);
                JOptionPane.showMessageDialog(this, mensajeEliminar);
            }
            
            LimpiarCampos();      
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID del cliente debe ser válido.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID de cliente para eliminar.");
    }
        
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnguadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguadarActionPerformed
        guardarCliente();
    }//GEN-LAST:event_btnguadarActionPerformed

    private void etiqidclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etiqidclienteKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            consultarClientePorId(etiqidcliente.getText().trim());
        }
        
    }//GEN-LAST:event_etiqidclienteKeyPressed

    private void btnaactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaactualizarActionPerformed
        actualizarCliente();
    }//GEN-LAST:event_btnaactualizarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        consultarClientePorId(etiqidcliente.getText().trim());
    }//GEN-LAST:event_btnconsultarActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateIngreso;
    private javax.swing.JButton btnaactualizar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguadar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbestado;
    private javax.swing.JTextField etiqidcliente;
    private javax.swing.JTextField etiqidpersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtestado;
    private javax.swing.JLabel txtidcliente;
    private javax.swing.JLabel txtidpersona;
    private javax.swing.JLabel txtingreso;
    // End of variables declaration//GEN-END:variables
}
